[package]
name = "tapa-micro-mailer"
version = "0.1.0"
authors = ["Aditya Kresna <kresna@tapalogi.com>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.61"
